INSERT INTO price_list (treatment,price) VALUES ('Breast biopsy', 8679);
INSERT INTO price_list (treatment,price) VALUES ('Coronary artery bypass', 8776);
INSERT INTO price_list (treatment,price) VALUES ('Coronary artery bypass', 949);
INSERT INTO price_list (treatment,price) VALUES ('Carotid endarterectomy', 1426);
INSERT INTO price_list (treatment,price) VALUES ('Cholecystectomy', 2574);
INSERT INTO price_list (treatment,price) VALUES ('Debridement of wound', 7076);
INSERT INTO price_list (treatment,price) VALUES ('Debridement of wound', 9123);
INSERT INTO price_list (treatment,price) VALUES ('Appendectomy', 2904);
INSERT INTO price_list (treatment,price) VALUES ('Appendectomy', 3680);
INSERT INTO price_list (treatment,price) VALUES ('Cholecystectomy', 4042);
INSERT INTO patients (name,surname,insured) VALUES ('Logan', 'Jackson', TRUE);
INSERT INTO patients (name,surname,insured) VALUES ('James', 'Smith', TRUE);
INSERT INTO patients (name,surname,insured) VALUES ('Olivia', 'Thomson', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Lucas', 'Jackson', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Isabella', 'White', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Mia', 'Johnson', TRUE);
INSERT INTO patients (name,surname,insured) VALUES ('Ava', 'Brown', TRUE);
INSERT INTO patients (name,surname,insured) VALUES ('Sophia', 'Brown', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Charlotte', 'Jackson', TRUE);
INSERT INTO patients (name,surname,insured) VALUES ('Oliver', 'Brown', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Mia', 'White', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Logan', 'Brown', TRUE);
INSERT INTO patients (name,surname,insured) VALUES ('Harper', 'Smith', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Mia', 'Grimes', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Evelyn', 'Robinson', TRUE);
INSERT INTO patients (name,surname,insured) VALUES ('William', 'White', TRUE);
INSERT INTO patients (name,surname,insured) VALUES ('Noah', 'Williams', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Mia', 'Robinson', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Mia', 'Thomson', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Sophia', 'Brown', TRUE);
INSERT INTO patients (name,surname,insured) VALUES ('Olivia', 'Williams', TRUE);
INSERT INTO patients (name,surname,insured) VALUES ('Lucas', 'Jackson', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Lucas', 'Johnson', TRUE);
INSERT INTO patients (name,surname,insured) VALUES ('Liam', 'Thomson', TRUE);
INSERT INTO patients (name,surname,insured) VALUES ('Harper', 'Grimes', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Emma', 'Robinson', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('James', 'White', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Evelyn', 'Smith', TRUE);
INSERT INTO patients (name,surname,insured) VALUES ('Elijah', 'Johnson', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Amelia', 'Thomson', TRUE);
INSERT INTO doctors (name,surname,specialist) VALUES ('Liam', 'Grimes',' Plastic surgery');
INSERT INTO doctors (name,surname,specialist) VALUES ('William', 'Grimes',' Radiology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Oliver', 'Jackson',' Dermatology');
INSERT INTO doctors (name,surname,specialist) VALUES ('James', 'White',' Orthopedics');
INSERT INTO doctors (name,surname,specialist) VALUES ('Noah', 'Smith',' Radiology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Harper', 'Brown',' Cardiology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Mason', 'Robinson',' Dermatology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Evelyn', 'Williams',' Cardiology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Charlotte', 'Thomson',' Radiology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Mason', 'Thomson',' Radiology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Charlotte', 'Johnson',' Cardiology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Mason', 'Grimes',' Dermatology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Lucas', 'Smith',' Plastic surgery');
INSERT INTO doctors (name,surname,specialist) VALUES ('Emma', 'Smith',' Radiology');
INSERT INTO doctors (name,surname,specialist) VALUES ('James', 'Robinson',' Plastic surgery');
INSERT INTO doctors (name,surname,specialist) VALUES ('Mason', 'Smith',' Orthopedics');
INSERT INTO doctors (name,surname,specialist) VALUES ('Isabella', 'Jackson',' Orthopedics');
INSERT INTO doctors (name,surname,specialist) VALUES ('Elijah', 'White',' Dermatology');
INSERT INTO doctors (name,surname,specialist) VALUES ('William', 'Thomson',' Orthopedics');
INSERT INTO doctors (name,surname,specialist) VALUES ('Olivia', 'White',' Cardiology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Noah', 'Robinson',' Plastic surgery');
INSERT INTO doctors (name,surname,specialist) VALUES ('William', 'White',' Cardiology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Olivia', 'Jackson',' Cardiology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Charlotte', 'Johnson',' Orthopedics');
INSERT INTO doctors (name,surname,specialist) VALUES ('Emma', 'White',' Plastic surgery');
INSERT INTO doctors (name,surname,specialist) VALUES ('Ava', 'Thomson',' Dermatology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Benjamin', 'Johnson',' Plastic surgery');
INSERT INTO doctors (name,surname,specialist) VALUES ('Sophia', 'Johnson',' Radiology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Emma', 'Johnson',' Cardiology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Mason', 'Grimes',' Orthopedics');
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2007-03-15',2481,27,12);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2009-11-12',6366,25,25);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2006-09-18',7014,13,1);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2011-06-27',670,24,15);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2009-02-25',1285,27,29);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2001-11-23',2529,22,9);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2010-09-18',3889,26,19);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2013-02-07',4317,2,8);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2010-12-21',1185,28,16);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2009-06-16',2419,23,23);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2004-01-25',447,8,6);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2012-11-19',7011,4,23);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2011-05-01',4690,22,19);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2002-03-28',2723,22,10);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2003-08-14',2864,18,4);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2005-09-09',3479,25,16);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2006-12-16',4423,11,21);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2004-06-13',2396,15,7);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2000-09-24',2850,27,26);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2003-03-29',3348,20,22);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2003-12-27',8229,17,26);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2005-05-28',2532,25,21);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2009-04-08',7898,30,8);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2007-04-20',8459,24,18);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2003-09-30',9655,2,5);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2003-04-11',3470,15,8);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2005-05-23',9049,17,17);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2001-12-21',4197,26,10);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2001-10-31',3287,30,14);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2010-11-22',7461,23,27);
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (15,16,'2000-12-26','Cataract surgery','didnt pay in time');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (30,16,'2004-12-19','Cesarean section','remove lung');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (1,26,'2004-09-16','Carotid endarterectomy','didnt pay in time');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (1,9,'2003-10-11','Breast biopsy','psycho');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (13,11,'2012-11-05','Cholecystectomy','psycho');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (15,24,'2007-11-02','Cataract surgery','psycho');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (18,27,'2002-04-30','Breast biopsy','remove lung');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (21,5,'2007-11-11','Cesarean section','remove lung');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (5,22,'2001-04-09','Cesarean section','psycho');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (24,1,'2000-08-08','Appendectomy','didnt pay in time');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (20,29,'2004-01-01','Cataract surgery','psycho');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (27,27,'2003-02-18','Breast biopsy','didnt pay in time');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (7,30,'2007-08-03','Appendectomy','psycho');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (27,22,'2013-01-18','Cataract surgery','didnt pay in time');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (1,24,'2013-01-29','Breast biopsy','psycho');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (16,9,'2005-01-24','Cesarean section','psycho');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (5,16,'2001-01-07','Breast biopsy','didnt pay in time');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (11,8,'2003-08-31','Carotid endarterectomy','remove lung');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (21,8,'2009-07-15','Appendectomy','psycho');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (26,9,'2009-03-26','Appendectomy','remove lung');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (5,10,'2006-06-30','Cholecystectomy','didnt pay in time');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (12,21,'2012-01-13','Coronary artery bypass','didnt pay in time');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (27,2,'2013-04-10','Debridement of wound','psycho');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (14,1,'2010-10-08','Appendectomy','didnt pay in time');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (9,13,'2008-03-31','Coronary artery bypass','remove lung');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (30,30,'2010-04-18','Coronary artery bypass','psycho');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (21,17,'2001-07-04','Breast biopsy','didnt pay in time');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (25,19,'2005-10-08','Cataract surgery','remove lung');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (3,25,'2007-03-31','Cholecystectomy','didnt pay in time');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (28,3,'2010-10-03','Cesarean section','psycho');
INSERT INTO medical_facility (name,localization,doctor_count,patient_count,contact_number) VALUES ('Hospital', 'New York', 3, 4, 627329649);
INSERT INTO medical_facility (name,localization,doctor_count,patient_count,contact_number) VALUES ('Hospital', 'Warsaw', 2, 8, 983889932);
INSERT INTO medical_facility (name,localization,doctor_count,patient_count,contact_number) VALUES ('Clinic', 'New York', 19, 5, 121989038);
INSERT INTO medical_facility (name,localization,doctor_count,patient_count,contact_number) VALUES ('Hospital', 'Berlin', 22, 16, 836211797);
INSERT INTO medical_facility (name,localization,doctor_count,patient_count,contact_number) VALUES ('Clinic', 'New York', 13, 13, 791691524);

