INSERT INTO price_list (treatment,price) VALUES ('Breast biopsy', 8679);
INSERT INTO price_list (treatment,price) VALUES ('Coronary artery bypass', 8776);
INSERT INTO price_list (treatment,price) VALUES ('Coronary artery bypass', 949);
INSERT INTO price_list (treatment,price) VALUES ('Carotid endarterectomy', 1426);
INSERT INTO price_list (treatment,price) VALUES ('Cholecystectomy', 2574);
INSERT INTO price_list (treatment,price) VALUES ('Debridement of wound', 7076);
INSERT INTO price_list (treatment,price) VALUES ('Debridement of wound', 9123);
INSERT INTO price_list (treatment,price) VALUES ('Appendectomy', 2904);
INSERT INTO price_list (treatment,price) VALUES ('Appendectomy', 3680);
INSERT INTO price_list (treatment,price) VALUES ('Cholecystectomy', 4042);

INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Mia', 'Khalifa', 'm_kfalifa@poczta.pl', '(.)(.)Mia69', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Eva', 'Elfie', 'e_elf@op.pl', 'Elfie123Up&Down', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Elsa', 'Jean', 'e.jean@gmail.com', 'JeanE8987!', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Lisa', 'Ann', 'ann_lisa@gmail.com', 'LisaA2020nn@', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Johnny', 'Sins', 'doctor_sins@sins.com', 'DontBeAfraidOfDoctor6969!', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Gabbie', 'Carter', 'g.carter@wp.pl', 'HelloPatient1234&', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Logan', 'Jackson', 'jackson@gmail.com', 'Jackson2044#', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Liam', 'Grimes', 'liam_grimes@op.pl', 'DontStopGrimes1346$', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('William', 'Grimes', 'william_g@gmail.com', 'HejHoHejHo909&', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('James', 'Smith', 'james_smith@op.pl', 'DoDomuBySieSzlo999#', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Olivia', 'Thomson', 'olivia_t@poczta.pl', 'Thomson373!', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Oliver', 'Jackson', 'oliver_jackson@gmail.com', 'PiejoKuryPiejo8669$', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('James', 'White', 'james_white@op.pl', 'NieMajoKoguta6969$', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Noah', 'Smith', 'noah_smith@gmail.com', 'AirWick0383@', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Harper', 'Brown', 'h_brown@poczta.pl', 'PumpkinBy999!', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Lucas', 'Jackson', 'jackson_l@jackson.com', 'Jblbbltinb083%', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Isabella', 'White', 'isabella_white@white.com', '999WhiteLike#FFFFFF', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Mia', 'Johnson', 'm.johnson@wp.pl', 'BlackLike#000000', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Mason', 'Robinson', 'mason_robinson@doctor.com', 'SmileEveryDay69!', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Ava', 'Brown', 'ava_brown@brown.com', 'Password123#', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Sophia', 'Brown', 's.brown@gmail.com', 'BrownLike#331900', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Charlotte', 'Jackson', 'charlotte_jackson@poczta.pl', 'JacksonHere999@', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Oliver', 'Brown', 'oliver.brown@op.pl', 'BrownEverywhere6060#', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Mia', 'White', 'mia_white@gmail.com', '#FFFFFFLikeWhite9000', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Evelyn', 'Williams', 'evelyn@williams.pl', 'Evelyn837465#', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Charlotte', 'Thomson', 'c_thomson@wp.pl', 'aaaaaaaaaBC23344^', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Mason', 'Thomson', 'mason@thomson@.com', 'XYZ98765$', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Logan', 'Brown', 'logan_b@op.pl', 'Logan98765$', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Harper', 'Smith', 'harper90@gmail.com', 'Harper9876543E$', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Charlotte', 'Johnson', 'oh_charlotte@buziaczek.pl', 'SweetCharlotte987654&', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Mason', 'Grimes', 'mason69@grimes.com', 'Grimes0256673$', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Lucas', 'Smith', 'lucas.smith@op.pl', 'Lucas0965Smith$', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Emma', 'Smith', 'em_ma@smith.com', 'Em2020ma1010Smith%', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('James', 'Robinson', 'j_robin@son.com', 'TooMuchSameSurname0987654@', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Mason', 'Smith', 'mas_on_smith@.gmail.com', 'AndWithSameName3456789#', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Mia', 'Grimes', 'again_grimes@gmail.com', 'ISeeGrimesEverywhere0987@', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Evelyn', 'Robinson', 'eve.rob@poczta.pl', 'AndRobinson987#', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('William', 'White', 'wil.white@.op.pl', 'WhiteLikeSnow87632!', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Noah', 'Williams', 'noah_will@gmail.com', 'JiggleBells9876@', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Isabella', 'Jackson', 'jackson_isa@wp.pl', '@AteThisBanana69', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Mia', 'Robinson', 'mia.robin@op.pl', 'Flowers987654#', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Elijah', 'White', 'elijah_white@gmail.com', 'BigBoss987#', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Mia', 'Thomson', 'mia@thomson.com', 'Thomson456#', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('William', 'Thomson', 'will.thom@gmail.com', 'William987654#', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Olivia', 'White', 'olivia@white.com', 'RoseAreRed1245#', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Noah', 'Robinson', 'robinson.noah@.op.pl', 'Noah987654Robinson#', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('William', 'White', 'william@white.com', 'William@white987654', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Olivia', 'Jackson', 'olivia.j@med.com', 'NoPassword9876543#', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Sophia', 'Brown', 'sophia.brown@op.pl','SophiaBrown098765432%', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Charlotte', 'Johnson', 'char.john@gmail.com', 'ThisIsPassword987654$', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Emma', 'White', 'white@emma.com', 'Plants09876543#', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Ava', 'Thomson', 'ava.thomson@gmail.com', 'PrettyPassword23532#', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Benjamin', 'Johnson', 'benjamin@johnson.com', 'Benjamin09876543&', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Olivia', 'Williams', 'o_williams@gmail.com', 'Blank456789#', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Lucas', 'Jackson', 'empty@emial.com', 'EmptyPassword9876543*', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Sophia', 'Johnson', 'soph.john@med.com', 'MedHere09765@', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Emma', 'Johnson', 'johnson@emma.com', 'Johnson&Johnson9876543', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Lucas', 'Johnson', 'johnson@johnson.com', 'HelloJohnson45789#', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Liam', 'Thomson', 'thomson@thomson.com', 'AndHelloThomson9876543&', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Harper', 'Grimes', 'harper_grimes@wp.pl', 'Harper345678%', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Mason', 'Grimes', 'mason@grimes.com', 'NextGrimes345@', 'ROLE_DOCTOR', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Emma', 'Robinson', 'em.rob@poczta.pl', 'Earth456789&', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('James', 'White', 'james.white@gmail.com', 'JamesWhite567%', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Evelyn', 'Smith', 'evelyn_smith@op.pl', 'EvelynSmith843#', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Elijah', 'Johnson', 'elijah.johnson@wp.pl', 'Elijah9876%^', 'ROLE_PATIENT', TRUE);
INSERT INTO users(name,surname,email,password,role,is_active) VALUES ('Amelia', 'Thomson', 'amelia.thomson@gmail.com', 'NicePatient876#', 'ROLE_PATIENT', TRUE);

INSERT INTO patients (user_id,insured) VALUES (2, TRUE);
INSERT INTO patients (user_id,insured) VALUES (3, TRUE);
INSERT INTO patients (user_id,insured) VALUES (4, FALSE);
INSERT INTO patients (user_id,insured) VALUES (7, FALSE);
INSERT INTO patients (user_id,insured) VALUES (10, TRUE);
INSERT INTO patients (user_id,insured) VALUES (11, FALSE);
INSERT INTO patients (user_id,insured) VALUES (16, FALSE);
INSERT INTO patients (user_id,insured) VALUES (17, FALSE);
INSERT INTO patients (user_id,insured) VALUES (18, TRUE);
INSERT INTO patients (user_id,insured) VALUES (20, TRUE);
INSERT INTO patients (user_id,insured) VALUES (21, FALSE);
INSERT INTO patients (user_id,insured) VALUES (22, TRUE);
INSERT INTO patients (user_id,insured) VALUES (23, FALSE);
INSERT INTO patients (user_id,insured) VALUES (24, FALSE);
INSERT INTO patients (user_id,insured) VALUES (28, TRUE);
INSERT INTO patients (user_id,insured) VALUES (29, FALSE);
INSERT INTO patients (user_id,insured) VALUES (36, FALSE);
INSERT INTO patients (user_id,insured) VALUES (37, TRUE);
INSERT INTO patients (user_id,insured) VALUES (38, TRUE);
INSERT INTO patients (user_id,insured) VALUES (39, FALSE);
INSERT INTO patients (user_id,insured) VALUES (41, FALSE);
INSERT INTO patients (user_id,insured) VALUES (43, FALSE);
INSERT INTO patients (user_id,insured) VALUES (49, TRUE);
INSERT INTO patients (user_id,insured) VALUES (54, TRUE);
INSERT INTO patients (user_id,insured) VALUES (55, FALSE);
INSERT INTO patients (user_id,insured) VALUES (58, TRUE);
INSERT INTO patients (user_id,insured) VALUES (59, TRUE);
INSERT INTO patients (user_id,insured) VALUES (60, FALSE);
INSERT INTO patients (user_id,insured) VALUES (62, FALSE);
INSERT INTO patients (user_id,insured) VALUES (63, FALSE);
INSERT INTO patients (user_id,insured) VALUES (64, TRUE);
INSERT INTO patients (user_id,insured) VALUES (65, FALSE);
INSERT INTO patients (user_id,insured) VALUES (66, TRUE);

INSERT INTO doctors (user_id,specialist) VALUES (1,' Plastic surgery');
INSERT INTO doctors (user_id,specialist) VALUES (5,' Gynecologist');
INSERT INTO doctors (user_id,specialist) VALUES (6,' Gynecologist');
INSERT INTO doctors (user_id,specialist) VALUES (8,' Plastic surgery');
INSERT INTO doctors (user_id,specialist) VALUES (9,' Radiology');
INSERT INTO doctors (user_id,specialist) VALUES (12,' Dermatology');
INSERT INTO doctors (user_id,specialist) VALUES (13,' Orthopedics');
INSERT INTO doctors (user_id,specialist) VALUES (14,' Radiology');
INSERT INTO doctors (user_id,specialist) VALUES (15,' Cardiology');
INSERT INTO doctors (user_id,specialist) VALUES (19,' Dermatology');
INSERT INTO doctors (user_id,specialist) VALUES (25,' Cardiology');
INSERT INTO doctors (user_id,specialist) VALUES (26,' Radiology');
INSERT INTO doctors (user_id,specialist) VALUES (27,' Radiology');
INSERT INTO doctors (user_id,specialist) VALUES (30,' Cardiology');
INSERT INTO doctors (user_id,specialist) VALUES (31,' Dermatology');
INSERT INTO doctors (user_id,specialist) VALUES (32,' Plastic surgery');
INSERT INTO doctors (user_id,specialist) VALUES (33,' Radiology');
INSERT INTO doctors (user_id,specialist) VALUES (34,' Plastic surgery');
INSERT INTO doctors (user_id,specialist) VALUES (35,' Orthopedics');
INSERT INTO doctors (user_id,specialist) VALUES (40,' Orthopedics');
INSERT INTO doctors (user_id,specialist) VALUES (42,' Dermatology');
INSERT INTO doctors (user_id,specialist) VALUES (44,' Orthopedics');
INSERT INTO doctors (user_id,specialist) VALUES (45,' Cardiology');
INSERT INTO doctors (user_id,specialist) VALUES (46,' Plastic surgery');
INSERT INTO doctors (user_id,specialist) VALUES (47,' Cardiology');
INSERT INTO doctors (user_id,specialist) VALUES (48,' Cardiology');
INSERT INTO doctors (user_id,specialist) VALUES (50,' Orthopedics');
INSERT INTO doctors (user_id,specialist) VALUES (51,' Plastic surgery');
INSERT INTO doctors (user_id,specialist) VALUES (52,' Dermatology');
INSERT INTO doctors (user_id,specialist) VALUES (53,' Plastic surgery');
INSERT INTO doctors (user_id,specialist) VALUES (56,' Radiology');
INSERT INTO doctors (user_id,specialist) VALUES (57,' Cardiology');
INSERT INTO doctors (user_id,specialist) VALUES (61,' Orthopedics');

INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2007-03-15',2481,30,15);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2009-11-12',6366,28,28);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2006-09-18',7014,16,4);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2011-06-27',670,27,18);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2009-02-25',1285,30,32);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2001-11-23',2529,25,12);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2010-09-18',3889,29,22);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2013-02-07',4317,5,11);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2010-12-21',1185,31,19);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2009-06-16',2419,26,26);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2004-01-25',447,11,9);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2012-11-19',7011,7,26);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2011-05-01',4690,25,22);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2002-03-28',2723,25,13);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2003-08-14',2864,21,7);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2005-09-09',3479,28,19);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2006-12-16',4423,14,24);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2004-06-13',2396,18,10);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2000-09-24',2850,30,29);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2003-03-29',3348,23,24);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2003-12-27',8229,20,29);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2005-05-28',2532,28,24);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2009-04-08',7898,33,11);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2007-04-20',8459,27,21);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2003-09-30',9655,5,8);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2003-04-11',3470,18,11);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2005-05-23',9049,20,20);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2001-12-21',4197,29,13);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2001-10-31',3287,33,17);
INSERT INTO appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2010-11-22',7461,26,30);

INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (18,19,'2000-12-26','Cataract surgery','didnt pay in time');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (33,19,'2004-12-19','Cesarean section','remove lung');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (4,29,'2004-09-16','Carotid endarterectomy','didnt pay in time');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (4,12,'2003-10-11','Breast biopsy','psycho');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (16,14,'2012-11-05','Cholecystectomy','psycho');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (18,27,'2007-11-02','Cataract surgery','psycho');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (21,30,'2002-04-30','Breast biopsy','remove lung');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (24,11,'2007-11-11','Cesarean section','remove lung');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (8,25,'2001-04-09','Cesarean section','psycho');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (27,4,'2000-08-08','Appendectomy','didnt pay in time');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (23,32,'2004-01-01','Cataract surgery','psycho');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (30,30,'2003-02-18','Breast biopsy','didnt pay in time');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (10,33,'2007-08-03','Appendectomy','psycho');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (30,25,'2013-01-18','Cataract surgery','didnt pay in time');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (4,27,'2013-01-29','Breast biopsy','psycho');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (1,2,'2015-12-24','Gonorrhea','psycho');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (19,12,'2005-01-24','Cesarean section','psycho');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (8,19,'2001-01-07','Breast biopsy','didnt pay in time');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (14,11,'2003-08-31','Carotid endarterectomy','remove lung');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (24,11,'2009-07-15','Appendectomy','psycho');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (29,12,'2009-03-26','Appendectomy','remove lung');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (8,13,'2006-06-30','Cholecystectomy','didnt pay in time');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (15,24,'2012-01-13','Coronary artery bypass','didnt pay in time');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (30,5,'2013-04-10','Debridement of wound','psycho');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (17,4,'2010-10-08','Appendectomy','didnt pay in time');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (12,16,'2008-03-31','Coronary artery bypass','remove lung');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (33,33,'2010-04-18','Coronary artery bypass','psycho');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (24,20,'2001-07-04','Breast biopsy','didnt pay in time');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (28,22,'2005-10-08','Cataract surgery','remove lung');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (6,28,'2007-03-31','Cholecystectomy','didnt pay in time');
INSERT INTO Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (31,6,'2010-10-03','Cesarean section','psycho');

INSERT INTO medical_facility (name,localization,doctor_count,patient_count,contact_number) VALUES ('Hospital', 'New York', 3, 4, 627329649);
INSERT INTO medical_facility (name,localization,doctor_count,patient_count,contact_number) VALUES ('Hospital', 'Warsaw', 2, 8, 983889932);
INSERT INTO medical_facility (name,localization,doctor_count,patient_count,contact_number) VALUES ('Clinic', 'New York', 19, 5, 121989038);
INSERT INTO medical_facility (name,localization,doctor_count,patient_count,contact_number) VALUES ('Hospital', 'Berlin', 22, 16, 836211797);
INSERT INTO medical_facility (name,localization,doctor_count,patient_count,contact_number) VALUES ('Clinic', 'New York', 13, 13, 791691524);

