INSERT INTO healthcare.price_list (treatment,price) VALUES ('Breast biopsy', 8679);
INSERT INTO healthcare.price_list (treatment,price) VALUES ('Coronary artery bypass', 8776);
INSERT INTO healthcare.price_list (treatment,price) VALUES ('Coronary artery bypass', 949);
INSERT INTO healthcare.price_list (treatment,price) VALUES ('Carotid endarterectomy', 1426);
INSERT INTO healthcare.price_list (treatment,price) VALUES ('Cholecystectomy', 2574);
INSERT INTO healthcare.price_list (treatment,price) VALUES ('Debridement of wound', 7076);
INSERT INTO healthcare.price_list (treatment,price) VALUES ('Debridement of wound', 9123);
INSERT INTO healthcare.price_list (treatment,price) VALUES ('Appendectomy', 2904);
INSERT INTO healthcare.price_list (treatment,price) VALUES ('Appendectomy', 3680);
INSERT INTO healthcare.price_list (treatment,price) VALUES ('Cholecystectomy', 4042);

INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Mia', 'Khalifa', 'm_kfalifa@poczta.pl', '$2a$10$0qHIW6Gxq0MIJIuiTz0fDeqV3Ug.KbFiI1zUM.ybIsO6L57yag6m.', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Eva', 'Elfie', 'e_elf@op.pl', '$2a$10$KrqrfA3OsQgp5FOkx5EO.eRDZT71h6pvOEV5M53UHDsegkwJhrfQW', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Elsa', 'Jean', 'e.jean@gmail.com', '$2a$10$yYAXUXpNg4OmsnUiY.q3yeEMNz3Be6h8RfR1rtmwSRPph86ZOUQ4S', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Lisa', 'Ann', 'ann_lisa@gmail.com', '$2a$10$kGPiO8W5ESdszOrBvFEibOHtTgJbMFRdsDfJfdWru1WOUAsWyDkDa', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Johnny', 'Sins', 'doctor_sins@sins.com', '$2a$10$pUCIZQbiQygy363KXUy6GOdkQwHlsVo/7XTZ0kLwjVTVn1T7XIOAO', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Gabbie', 'Carter', 'g.carter@wp.pl', '$2a$10$U6WNU8VVQkIP39x3nFQjve7PFjgSHFzjd6vwz0sLZP2YHoQKk8C4i', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Logan', 'Jackson', 'jackson@gmail.com', '$2a$10$2j/OD1OckOJwxliuZbKhGOdDK7JpsygfXuqTVKqdcTCRUE1Eq24Y2', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Liam', 'Grimes', 'liam_grimes@op.pl', '$2a$10$wBK9yBO2LOW0rAI15KOUNOPVNYq.kWJ5MKKRFGrjp.af49RnLe2xe', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('William', 'Grimes', 'william_g@gmail.com', '$2a$10$zUE.qneSWy.s04bpdntbBe.ATTCiDzqcOIJIsL4e.ANawdK/.8Jh2', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('James', 'Smith', 'james_smith@op.pl', '$2a$10$498PbNfPMAwlKYu6ahprLuj/S1I0Tra9vQQw4QXWMYGImuTgZHxUy', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Olivia', 'Thomson', 'olivia_t@poczta.pl', '$2a$10$GTGo4R8uaa/uPMENm6ECgO9d7tMbPLpBhmD1FUIMjjiOmjyzO04ia', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Oliver', 'Jackson', 'oliver_jackson@gmail.com', '$2a$10$crQUCbZvR6bD2RgYI2KTnu.vsr5cy165kfaehX2gbZeVTGuiB1SaC', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('James', 'White', 'james_white@op.pl', '$2a$10$dHUcaasXaDxvqKeCIO6lhelLmfgi50Xgy9NUioUXOGMydedCGy23i', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Noah', 'Smith', 'noah_smith@gmail.com', '$2a$10$u3.g3HatrdP9eB8uzYq2iOUBva7eKXzRuwldoFenDfDDQXJvaoJWm', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Harper', 'Brown', 'h_brown@poczta.pl', '$2a$10$pKxbkuVE1idiVv/Z3oWiD.iFBBSCqhRwETTz0WSBvJ.edkF.HJko.', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Lucas', 'Jackson', 'jackson_l@jackson.com', '$2a$10$zDYHgI0UzWCwbRH6koQ25.UYbm/iSm6NU7ZvjOh0d62RjF618lKC.', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Isabella', 'White', 'isabella_white@white.com', '$2a$10$2c/RMRxjSdMgd2xFqqippufJ.dfq24dVQw9EQf8Db9c/pJxJo6DA6', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Mia', 'Johnson', 'm.johnson@wp.pl', '$2a$10$ZDsJp8pOV8AFw6879CN8xer8kZBccy0JVWMuctjDMLYHhv6GyzFWW', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Mason', 'Robinson', 'mason_robinson@doctor.com', '$2a$10$sOiCjH3xldgwW7MMLSChm.sP7uc1c1sg.Rl454kEj4tnWIi5nmA5y', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Ava', 'Brown', 'ava_brown@brown.com', '$2a$10$KEH3vmR/zlDh2SghRyOXIOtHb11O7yJMW1CUgQyh5VULFGAAX/cAe', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Sophia', 'Brown', 's.brown@gmail.com', '$2a$10$0G5s3QDPUsmYpIh5kzPaK.nYklYIGhBp3A1lFtGVRlhOr0Katwmw.', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Charlotte', 'Jackson', 'charlotte_jackson@poczta.pl', '$2a$10$Y94HKU0rlst6VT/e4LySj.prGYG9Ivqqk0pg4Nj7rv9/36JjhCsTK', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Oliver', 'Brown', 'oliver.brown@op.pl', '$2a$10$xJLrlsI/xuZgLbmbx2HNA.4027LXPmAB0b4cJVl1MG.NHvJGf9PvC', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Mia', 'White', 'mia_white@gmail.com', '$2a$10$Fp5Alt/w9sCv.n1p3KDq7uaXP6d1HcIUuykBHGobCPshSyVEqgw1K', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Evelyn', 'Williams', 'evelyn@williams.pl', '$2a$10$OTonK8Ap4TT2wrF2ex8Mw.b5Bzok64aRJXWU.dnTESgBU.qcVY7CC', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Charlotte', 'Thomson', 'c_thomson@wp.pl', '$2a$10$KfFttpJsJPFD0jNsskOnuOt.4zsS353O/5OnAxPF3BOc1RSC8zdzm', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Mason', 'Thomson', 'mason@thomson@.com', '$2a$10$81mM1VJx/bFKi4c77ddoluvKriOIqBJHCcDNw0mU6.jf5tKHiPd8u', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Logan', 'Brown', 'logan_b@op.pl', '$2a$10$CUr87LEF2EOzuBjf1/jC2OAqIoehSoLZuDxU4uDUmZc2fIc6dsmmC', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Harper', 'Smith', 'harper90@gmail.com', '$2a$10$VG7T0PCpjfHlGGXZgq0hQu0EjEGAQGO/jjWTPzQJGnGIciCQeLdIO', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Charlotte', 'Johnson', 'oh_charlotte@buziaczek.pl', '$2a$10$KcHBwbLFzsw6rmq/MRzyRel5CWycYMH0vnG0kPvS76hpOO2YEFqO6', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Mason', 'Grimes', 'mason69@grimes.com', '$2a$10$JfL1/l60YDtF7F5dREEMqu9KNLF6YWmt5u960ExKjnxEu5dgNkxn2', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Lucas', 'Smith', 'lucas.smith@op.pl', '$2a$10$hWMMs9hljlDGkIT3Lvbr3.m3r4X3UhKSC4zi.QOrbLUoqUX.Fhwpm', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Emma', 'Smith', 'em_ma@smith.com', '$2a$10$fquJF/uwoASqizIKCLmFaeCJCgdpmN4XOMoDhoTuZQhIZ9/eKeMGC', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('James', 'Robinson', 'j_robin@son.com', '$2a$10$XWyi1EaGYCB//9WkR3Pbyu9cpKzrEdDaWnsI3Zol1OzG8/q.hF9oe', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Mason', 'Smith', 'mas_on_smith@.gmail.com', '$2a$10$tEwG4qj8Fjk3nrBJwUgHPeNOy8Yu4gGcIu36q.avt35.nXzTfwkBq', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Mia', 'Grimes', 'again_grimes@gmail.com', '$2a$10$Vg1VqrmGZlu6c70UQ7WarOzO4hn1c4gbbJo2AcWdsp8BJ9WuiCUcu', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Evelyn', 'Robinson', 'eve.rob@poczta.pl', '$2a$10$rF7JpRiZI0hwePhH1b.mgOnweltv9TyeUh9NeR/tjWjI0l1aghmZm', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('William', 'White', 'wil.white@.op.pl', '$2a$10$tUKufkmfStxAG9Kfp54hR.7ee3rx.j2UrMQrRlBzIzhof1osrbH76', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Noah', 'Williams', 'noah_will@gmail.com', '$2a$10$B4TdnGA92cfiy0n.JG2gJeL5H70ebpXqUEJcj1En9CAzWGiMmonnW', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Isabella', 'Jackson', 'jackson_isa@wp.pl', '$2a$10$eRwa5kk1gZ/Bj.9Y1T3BX.zbfJSX7OPVJlIC7ZKIW1sieXz71g.Fi', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Mia', 'Robinson', 'mia.robin@op.pl', '$2a$10$vDP3cxsrmTXKkAT3m7SAYOpl9VlYe.F.2UT9IXOu4ghONDxSQhsXS', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Elijah', 'White', 'elijah_white@gmail.com', '$2a$10$9.gBA7BbwXjzpfgBcduSueBT1ljIe0wDA/uEgOVX6naU2EGMFI43K', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Mia', 'Thomson', 'mia@thomson.com', '$2a$10$yqOVI3pJCpssVqEJR8kz0.A8Bm3mz7.5v10XAbHArJHn/Rt/FD542', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('William', 'Thomson', 'will.thom@gmail.com', '$2a$10$OU8uR3iqJdQRxSILpijMHOnyEsJVhDPGJCBIeeQ.Ebg5jnETmd.qW', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Olivia', 'White', 'olivia@white.com', '$2a$10$6tZfalms75YRiDlc1GtNQ.gMib7pwu3K7HtR4Fh/Wf4.HStlG2pba', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Noah', 'Robinson', 'robinson.noah@.op.pl', '$2a$10$q.9xo1S2p6LNM7VbH5mJ7.3Lqamk78nR370.txF3sCFzLurV2i6mK', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('William', 'White', 'william@white.com', '$2a$10$Fl8ONM7Nu01L8d9r4Y9ca.sRXiWsUSdCeEgs2E5OneX0.ObauvP4K', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Olivia', 'Jackson', 'olivia.j@med.com', '$2a$10$vvwXiQDv.qwrMqOgA1uZ3OeRARnka9FZ4Y9lkm.V4rV3ad/06Rgsq', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Sophia', 'Brown', 'sophia.brown@op.pl','$2a$10$vCxOqNl2SzuYqg0X3BZYv.GgFPb9RzmIRzmRpozqaFgni5Qml1h6i', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Charlotte', 'Johnson', 'char.john@gmail.com', '$2a$10$5rEWUzYZjSSg6AJoQCBayeyFRB.suU034xjb29Hz5oXZ0Hex6PW6u', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Emma', 'White', 'white@emma.com', '$2a$10$ncXoA4DvkIYDCqHt16Y85OJDdAa0Jbmm3kzSY6wOYJgfrIgv1ewJC', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Ava', 'Thomson', 'ava.thomson@gmail.com', '$2a$10$kElRU.w7.7Wp4T4IHg5qc.zUiGytvQX7q2RB0suh0FX65okvRIEsS', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Benjamin', 'Johnson', 'benjamin@johnson.com', '$2a$10$akpUpMiZU.Km4OvCBiGrw.43YwD2.cogwcvSoRRM.7I66pTSzpuv6', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Olivia', 'Williams', 'o_williams@gmail.com', '$2a$10$H78nwfxvRPdxUKRcWMeg.upUlrryKOQc4qAy2kjIj1QMhJPW/p09a', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Lucas', 'Jackson', 'empty@emial.com', '$2a$10$XtTp9MMgXhLtvDg5BavxkOo6b.NjOiAAVTv8XBUfIUjecfg85mZWi', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Sophia', 'Johnson', 'soph.john@med.com', '$2a$10$riMn9IJUloaEc811amM6Ie1hJF003IOv9AE.G4yfWYdVMtMC0pSPC', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Emma', 'Johnson', 'johnson@emma.com', '$2a$10$r0ziBzO1k31LkRIjFV.EKORc.XeM8cEVC4R9BciIAmURNfLSvq8yy', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Lucas', 'Johnson', 'johnson@johnson.com', '$2a$10$pgAf2gT/lg9hfHjArjnGmubQPvkawOLm3RvQdO2RWb8kqvYSq0n7a', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Liam', 'Thomson', 'thomson@thomson.com', '$2a$10$DM1lniqJIZJJ6eAH2aa/iu3Kw8mikbUwACB.eUL/0G8A.PNP/eK1.', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Harper', 'Grimes', 'harper_grimes@wp.pl', '$2a$10$CfS6lqaqHrbutrZ7lqksvebepC5v1rXQ9OvTdwIgDTVnT9GzyubOe', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Mason', 'Grimes', 'mason@grimes.com', '$2a$10$W6JQ9ssBIE4nRCI4AXlht.sQREj.yvjvc4Mw84/Zq0jQz8BnJXggi', 'DOCTOR', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Emma', 'Robinson', 'em.rob@poczta.pl', '$2a$10$DHGqxBdyPHynO0HQUExjx.o.1s8FmHZ46QltSB7AAXGgoe.xd1FD.', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('James', 'White', 'james.white@gmail.com', '$2a$10$2RZKWRoG6SpDjErdeflVduu5xXZ3iYseQx/6F6K1swJVPbsgJohTu', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Evelyn', 'Smith', 'evelyn_smith@op.pl', '$2a$10$TpQoRRlcPextKvkdB3r6wuajvzqTx8QbCQ5G3LegCOtbcj0CniOzq', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Elijah', 'Johnson', 'elijah.johnson@wp.pl', '$2a$10$W22u5cHiM6Was4VKk0RQTupmMRYMx0hHHzB/ecwAQXvC2vBTCHDS6', 'PATIENT', TRUE);
INSERT INTO healthcare.users(name,surname,email,password,role,is_active) VALUES ('Amelia', 'Thomson', 'amelia.thomson@gmail.com', '$2a$10$wZQWYBhZS/0dIZbYDdWUU.jWX12t6ZH9SokX2Iu9kptXIK1s2MBZi', 'PATIENT', TRUE);

INSERT INTO healthcare.patients (user_id,insured) VALUES (2, TRUE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (3, TRUE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (4, FALSE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (7, FALSE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (10, TRUE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (11, FALSE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (16, FALSE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (17, FALSE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (18, TRUE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (20, TRUE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (21, FALSE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (22, TRUE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (23, FALSE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (24, FALSE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (28, TRUE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (29, FALSE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (36, FALSE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (37, TRUE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (38, TRUE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (39, FALSE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (41, FALSE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (43, FALSE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (49, TRUE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (54, TRUE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (55, FALSE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (58, TRUE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (59, TRUE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (60, FALSE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (62, FALSE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (63, FALSE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (64, TRUE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (65, FALSE);
INSERT INTO healthcare.patients (user_id,insured) VALUES (66, TRUE);

INSERT INTO healthcare.doctors (user_id,specialist) VALUES (1,' Plastic surgery');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (5,' Gynecologist');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (6,' Gynecologist');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (8,' Plastic surgery');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (9,' Radiology');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (12,' Dermatology');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (13,' Orthopedics');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (14,' Radiology');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (15,' Cardiology');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (19,' Dermatology');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (25,' Cardiology');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (26,' Radiology');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (27,' Radiology');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (30,' Cardiology');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (31,' Dermatology');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (32,' Plastic surgery');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (33,' Radiology');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (34,' Plastic surgery');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (35,' Orthopedics');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (40,' Orthopedics');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (42,' Dermatology');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (44,' Orthopedics');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (45,' Cardiology');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (46,' Plastic surgery');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (47,' Cardiology');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (48,' Cardiology');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (50,' Orthopedics');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (51,' Plastic surgery');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (52,' Dermatology');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (53,' Plastic surgery');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (56,' Radiology');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (57,' Cardiology');
INSERT INTO healthcare.doctors (user_id,specialist) VALUES (61,' Orthopedics');

INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2007-03-15',2481,30,15);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2009-11-12',6366,28,28);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2006-09-18',7014,16,4);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2011-06-27',670,27,18);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2009-02-25',1285,30,32);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2001-11-23',2529,25,12);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2010-09-18',3889,29,22);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2013-02-07',4317,5,11);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2010-12-21',1185,31,19);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2009-06-16',2419,26,26);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2004-01-25',447,11,9);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2012-11-19',7011,7,26);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2011-05-01',4690,25,22);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2002-03-28',2723,25,13);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2003-08-14',2864,21,7);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2005-09-09',3479,28,19);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2006-12-16',4423,14,24);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2004-06-13',2396,18,10);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2000-09-24',2850,30,29);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2003-03-29',3348,23,24);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2003-12-27',8229,20,29);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2005-05-28',2532,28,24);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2009-04-08',7898,33,11);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2007-04-20',8459,27,21);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2003-09-30',9655,5,8);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2003-04-11',3470,18,11);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2005-05-23',9049,20,20);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2001-12-21',4197,29,13);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2001-10-31',3287,33,17);
INSERT INTO healthcare.appointments ( appointment_date, cost,patient_id, doctor_id) VALUES ('2010-11-22',7461,26,30);

INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (18,19,'2000-12-26','Cataract surgery','didnt pay in time');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (33,19,'2004-12-19','Cesarean section','remove lung');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (4,29,'2004-09-16','Carotid endarterectomy','didnt pay in time');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (4,12,'2003-10-11','Breast biopsy','psycho');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (16,14,'2012-11-05','Cholecystectomy','psycho');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (18,27,'2007-11-02','Cataract surgery','psycho');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (21,30,'2002-04-30','Breast biopsy','remove lung');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (24,11,'2007-11-11','Cesarean section','remove lung');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (8,25,'2001-04-09','Cesarean section','psycho');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (27,4,'2000-08-08','Appendectomy','didnt pay in time');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (23,32,'2004-01-01','Cataract surgery','psycho');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (30,30,'2003-02-18','Breast biopsy','didnt pay in time');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (10,33,'2007-08-03','Appendectomy','psycho');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (30,25,'2013-01-18','Cataract surgery','didnt pay in time');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (4,27,'2013-01-29','Breast biopsy','psycho');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (1,2,'2015-12-24','Gonorrhea','psycho');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (19,12,'2005-01-24','Cesarean section','psycho');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (8,19,'2001-01-07','Breast biopsy','didnt pay in time');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (14,11,'2003-08-31','Carotid endarterectomy','remove lung');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (24,11,'2009-07-15','Appendectomy','psycho');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (29,12,'2009-03-26','Appendectomy','remove lung');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (8,13,'2006-06-30','Cholecystectomy','didnt pay in time');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (15,24,'2012-01-13','Coronary artery bypass','didnt pay in time');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (30,5,'2013-04-10','Debridement of wound','psycho');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (17,4,'2010-10-08','Appendectomy','didnt pay in time');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (12,16,'2008-03-31','Coronary artery bypass','remove lung');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (33,33,'2010-04-18','Coronary artery bypass','psycho');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (24,20,'2001-07-04','Breast biopsy','didnt pay in time');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (28,22,'2005-10-08','Cataract surgery','remove lung');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (6,28,'2007-03-31','Cholecystectomy','didnt pay in time');
INSERT INTO healthcare.Patients_med_data ( patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (31,6,'2010-10-03','Cesarean section','psycho');

INSERT INTO healthcare.medical_facility (name,localization,doctor_count,patient_count,contact_number) VALUES ('Hospital', 'New York', 3, 4, 627329649);
INSERT INTO healthcare.medical_facility (name,localization,doctor_count,patient_count,contact_number) VALUES ('Hospital', 'Warsaw', 2, 8, 983889932);
INSERT INTO healthcare.medical_facility (name,localization,doctor_count,patient_count,contact_number) VALUES ('Clinic', 'New York', 19, 5, 121989038);
INSERT INTO healthcare.medical_facility (name,localization,doctor_count,patient_count,contact_number) VALUES ('Hospital', 'Berlin', 22, 16, 836211797);
INSERT INTO healthcare.medical_facility (name,localization,doctor_count,patient_count,contact_number) VALUES ('Clinic', 'New York', 13, 13, 791691524);

