INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (1,15,16,'2000-12-26','Cataract surgery','didnt pay in time');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (2,30,16,'2004-12-19','Cesarean section','remove lung');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (3,1,26,'2004-09-16','Carotid endarterectomy','didnt pay in time');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (4,1,9,'2003-10-11','Breast biopsy','psycho');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (5,13,11,'2012-11-05','Cholecystectomy','psycho');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (6,15,24,'2007-11-02','Cataract surgery','psycho');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (7,18,27,'2002-04-30','Breast biopsy','remove lung');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (8,21,5,'2007-11-11','Cesarean section','remove lung');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (9,5,22,'2001-04-09','Cesarean section','psycho');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (10,24,1,'2000-08-08','Appendectomy','didnt pay in time');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (11,20,29,'2004-01-01','Cataract surgery','psycho');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (12,27,27,'2003-02-18','Breast biopsy','didnt pay in time');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (13,7,30,'2007-08-03','Appendectomy','psycho');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (14,27,22,'2013-01-18','Cataract surgery','didnt pay in time');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (15,1,24,'2013-01-29','Breast biopsy','psycho');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (16,16,9,'2005-01-24','Cesarean section','psycho');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (17,5,16,'2001-01-07','Breast biopsy','didnt pay in time');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (18,11,8,'2003-08-31','Carotid endarterectomy','remove lung');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (19,21,8,'2009-07-15','Appendectomy','psycho');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (20,26,9,'2009-03-26','Appendectomy','remove lung');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (21,5,10,'2006-06-30','Cholecystectomy','didnt pay in time');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (22,12,21,'2012-01-13','Coronary artery bypass','didnt pay in time');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (23,27,2,'2013-04-10','Debridement of wound','psycho');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (24,14,1,'2010-10-08','Appendectomy','didnt pay in time');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (25,9,13,'2008-03-31','Coronary artery bypass','remove lung');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (26,30,30,'2010-04-18','Coronary artery bypass','psycho');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (27,21,17,'2001-07-04','Breast biopsy','didnt pay in time');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (28,25,19,'2005-10-08','Cataract surgery','remove lung');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (29,3,25,'2007-03-31','Cholecystectomy','didnt pay in time');
INSERT INTO Patients_med_data (id, patient_id, doctor_id, treatment_date,additional_notes, medical_procedure) VALUES (30,28,3,'2010-10-03','Cesarean section','psycho');
