INSERT INTO doctors (id,name,surname,specialist) VALUES (1, 'Liam', 'Grimes',' Plastic surgery');
INSERT INTO doctors (id,name,surname,specialist) VALUES (2, 'William', 'Grimes',' Radiology');
INSERT INTO doctors (id,name,surname,specialist) VALUES (3, 'Oliver', 'Jackson',' Dermatology');
INSERT INTO doctors (id,name,surname,specialist) VALUES (4, 'James', 'White',' Orthopedics');
INSERT INTO doctors (id,name,surname,specialist) VALUES (5, 'Noah', 'Smith',' Radiology');
INSERT INTO doctors (id,name,surname,specialist) VALUES (6, 'Harper', 'Brown',' Cardiology');
INSERT INTO doctors (id,name,surname,specialist) VALUES (7, 'Mason', 'Robinson',' Dermatology');
INSERT INTO doctors (id,name,surname,specialist) VALUES (8, 'Evelyn', 'Williams',' Cardiology');
INSERT INTO doctors (id,name,surname,specialist) VALUES (9, 'Charlotte', 'Thomson',' Radiology');
INSERT INTO doctors (id,name,surname,specialist) VALUES (10, 'Mason', 'Thomson',' Radiology');
INSERT INTO doctors (id,name,surname,specialist) VALUES (11, 'Charlotte', 'Johnson',' Cardiology');
INSERT INTO doctors (id,name,surname,specialist) VALUES (12, 'Mason', 'Grimes',' Dermatology');
INSERT INTO doctors (id,name,surname,specialist) VALUES (13, 'Lucas', 'Smith',' Plastic surgery');
INSERT INTO doctors (id,name,surname,specialist) VALUES (14, 'Emma', 'Smith',' Radiology');
INSERT INTO doctors (id,name,surname,specialist) VALUES (15, 'James', 'Robinson',' Plastic surgery');
INSERT INTO doctors (id,name,surname,specialist) VALUES (16, 'Mason', 'Smith',' Orthopedics');
INSERT INTO doctors (id,name,surname,specialist) VALUES (17, 'Isabella', 'Jackson',' Orthopedics');
INSERT INTO doctors (id,name,surname,specialist) VALUES (18, 'Elijah', 'White',' Dermatology');
INSERT INTO doctors (id,name,surname,specialist) VALUES (19, 'William', 'Thomson',' Orthopedics');
INSERT INTO doctors (id,name,surname,specialist) VALUES (20, 'Olivia', 'White',' Cardiology');
INSERT INTO doctors (id,name,surname,specialist) VALUES (21, 'Noah', 'Robinson',' Plastic surgery');
INSERT INTO doctors (id,name,surname,specialist) VALUES (22, 'William', 'White',' Cardiology');
INSERT INTO doctors (id,name,surname,specialist) VALUES (23, 'Olivia', 'Jackson',' Cardiology');
INSERT INTO doctors (id,name,surname,specialist) VALUES (24, 'Charlotte', 'Johnson',' Orthopedics');
INSERT INTO doctors (id,name,surname,specialist) VALUES (25, 'Emma', 'White',' Plastic surgery');
INSERT INTO doctors (id,name,surname,specialist) VALUES (26, 'Ava', 'Thomson',' Dermatology');
INSERT INTO doctors (id,name,surname,specialist) VALUES (27, 'Benjamin', 'Johnson',' Plastic surgery');
INSERT INTO doctors (id,name,surname,specialist) VALUES (28, 'Sophia', 'Johnson',' Radiology');
INSERT INTO doctors (id,name,surname,specialist) VALUES (29, 'Emma', 'Johnson',' Cardiology');
INSERT INTO doctors (id,name,surname,specialist) VALUES (30, 'Mason', 'Grimes',' Orthopedics');
