INSERT INTO price_list (treatment,price) VALUES ('Breast biopsy', 8679);
INSERT INTO price_list (treatment,price) VALUES ('Coronary artery bypass', 8776);
INSERT INTO price_list (treatment,price) VALUES ('Coronary artery bypass', 949);
INSERT INTO price_list (treatment,price) VALUES ('Carotid endarterectomy', 1426);
INSERT INTO price_list (treatment,price) VALUES ('Cholecystectomy', 2574);
INSERT INTO price_list (treatment,price) VALUES ('Debridement of wound', 7076);
INSERT INTO price_list (treatment,price) VALUES ('Debridement of wound', 9123);
INSERT INTO price_list (treatment,price) VALUES ('Appendectomy', 2904);
INSERT INTO price_list (treatment,price) VALUES ('Appendectomy', 3680);
INSERT INTO price_list (treatment,price) VALUES ('Cholecystectomy', 4042);
INSERT INTO patients (name,surname,insured) VALUES ('Logan', 'Jackson', TRUE);
INSERT INTO patients (name,surname,insured) VALUES ('James', 'Smith', TRUE);
INSERT INTO patients (name,surname,insured) VALUES ('Olivia', 'Thomson', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Lucas', 'Jackson', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Isabella', 'White', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Mia', 'Johnson', TRUE);
INSERT INTO patients (name,surname,insured) VALUES ('Ava', 'Brown', TRUE);
INSERT INTO patients (name,surname,insured) VALUES ('Sophia', 'Brown', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Charlotte', 'Jackson', TRUE);
INSERT INTO patients (name,surname,insured) VALUES ('Oliver', 'Brown', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Mia', 'White', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Logan', 'Brown', TRUE);
INSERT INTO patients (name,surname,insured) VALUES ('Harper', 'Smith', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Mia', 'Grimes', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Evelyn', 'Robinson', TRUE);
INSERT INTO patients (name,surname,insured) VALUES ('William', 'White', TRUE);
INSERT INTO patients (name,surname,insured) VALUES ('Noah', 'Williams', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Mia', 'Robinson', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Mia', 'Thomson', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Sophia', 'Brown', TRUE);
INSERT INTO patients (name,surname,insured) VALUES ('Olivia', 'Williams', TRUE);
INSERT INTO patients (name,surname,insured) VALUES ('Lucas', 'Jackson', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Lucas', 'Johnson', TRUE);
INSERT INTO patients (name,surname,insured) VALUES ('Liam', 'Thomson', TRUE);
INSERT INTO patients (name,surname,insured) VALUES ('Harper', 'Grimes', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Emma', 'Robinson', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('James', 'White', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Evelyn', 'Smith', TRUE);
INSERT INTO patients (name,surname,insured) VALUES ('Elijah', 'Johnson', FALSE);
INSERT INTO patients (name,surname,insured) VALUES ('Amelia', 'Thomson', TRUE);
INSERT INTO doctors (name,surname,specialist) VALUES ('Liam', 'Grimes',' Plastic surgery');
INSERT INTO doctors (name,surname,specialist) VALUES ('William', 'Grimes',' Radiology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Oliver', 'Jackson',' Dermatology');
INSERT INTO doctors (name,surname,specialist) VALUES ('James', 'White',' Orthopedics');
INSERT INTO doctors (name,surname,specialist) VALUES ('Noah', 'Smith',' Radiology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Harper', 'Brown',' Cardiology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Mason', 'Robinson',' Dermatology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Evelyn', 'Williams',' Cardiology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Charlotte', 'Thomson',' Radiology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Mason', 'Thomson',' Radiology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Charlotte', 'Johnson',' Cardiology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Mason', 'Grimes',' Dermatology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Lucas', 'Smith',' Plastic surgery');
INSERT INTO doctors (name,surname,specialist) VALUES ('Emma', 'Smith',' Radiology');
INSERT INTO doctors (name,surname,specialist) VALUES ('James', 'Robinson',' Plastic surgery');
INSERT INTO doctors (name,surname,specialist) VALUES ('Mason', 'Smith',' Orthopedics');
INSERT INTO doctors (name,surname,specialist) VALUES ('Isabella', 'Jackson',' Orthopedics');
INSERT INTO doctors (name,surname,specialist) VALUES ('Elijah', 'White',' Dermatology');
INSERT INTO doctors (name,surname,specialist) VALUES ('William', 'Thomson',' Orthopedics');
INSERT INTO doctors (name,surname,specialist) VALUES ('Olivia', 'White',' Cardiology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Noah', 'Robinson',' Plastic surgery');
INSERT INTO doctors (name,surname,specialist) VALUES ('William', 'White',' Cardiology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Olivia', 'Jackson',' Cardiology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Charlotte', 'Johnson',' Orthopedics');
INSERT INTO doctors (name,surname,specialist) VALUES ('Emma', 'White',' Plastic surgery');
INSERT INTO doctors (name,surname,specialist) VALUES ('Ava', 'Thomson',' Dermatology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Benjamin', 'Johnson',' Plastic surgery');
INSERT INTO doctors (name,surname,specialist) VALUES ('Sophia', 'Johnson',' Radiology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Emma', 'Johnson',' Cardiology');
INSERT INTO doctors (name,surname,specialist) VALUES ('Mason', 'Grimes',' Orthopedics');
INSERT INTO medical_facility (name,localization,doctor_count,patient_count,contact_number) VALUES ('Hospital', 'New York', 3, 4, 627329649);
INSERT INTO medical_facility (name,localization,doctor_count,patient_count,contact_number) VALUES ('Hospital', 'Warsaw', 2, 8, 983889932);
INSERT INTO medical_facility (name,localization,doctor_count,patient_count,contact_number) VALUES ('Clinic', 'New York', 19, 5, 121989038);
INSERT INTO medical_facility (name,localization,doctor_count,patient_count,contact_number) VALUES ('Hospital', 'Berlin', 22, 16, 836211797);
INSERT INTO medical_facility (name,localization,doctor_count,patient_count,contact_number) VALUES ('Clinic', 'New York', 13, 13, 791691524);